### ISSUE TITLE
Empty heading

### ISSUE THREAD

**Issue by eggplants** [azu/github-sponsorable-in-japan#1]
Some headings are empty since some users have not set screen names.

```shell
# e3e076a
$ grep -Fc '[](' README.md
47
```

<img width="572" alt="スクリーンショット 2023-03-03 11 43 00" src="https://user-images.githubusercontent.com/42153744/222618207-ee9f25bc-6457-4376-9560-a8aa826e910f.png">

**Comment by azu** [comment]
Thanks!

```
$ grep -Fc '[](' README.md
0
```
